// ============================================================
// /module_curriculum_text.js  (3.77.0 — moved out of module_curriculum.js, code unchanged)
// Module Curriculum: the interface strings (_S, EN/FR/AR), the labels used
// in the exported curriculum (_L) and the two guidance texts (_GUIDE,
// _DIST_GUIDE). Text only; module_curriculum.js holds the logic.
// ============================================================


// ── Strings ──────────────────────────────────────────────────
// translations.js wins when it has the key (same rule as modules.js);
// these local tables keep the tab complete in all three languages.
export const _S = {
  en: {
    tabModuleCurriculum: 'Module Curriculum CUR/CBC',
    curEmptyTitle: 'No modules yet',
    curEmptyBody: 'The curriculum is written per module. Build your modules in Module Mapping first — they will appear here automatically.',
    curGoMM: 'Go to Module Mapping',
    curSelModule: 'Module',
    curPrev: 'Previous module',
    curNext: 'Next module',
    curComplete: '{p}% complete',
    curExportThis: 'Export this module (Word)',
    curSettings: 'Programme settings',
    curSettingsHint: 'Saved once for the whole project and used by every module. Hours and percentages are set in each module’s Time table.',
    curProgName: 'Programme name',
    curHpc: 'Hours per credit',
    curGroup: 'Learners per group',
    curSplitDefault: 'Default time split (%)',
    curSplitSum: 'Total: {n}%',
    curSplitBad: 'The percentages must add up to 100% (now {n}%). Hours are shared out in proportion until you fix it.',
    sec1: '1 · Module header',
    sec2: '2 · Learning outcomes',
    sec3: '3 · Module resources',
    curFromMM: 'From Module Mapping',
    curEditInMM: 'Edit in Module Mapping',
    curTitle: 'Module title',
    curLevel: 'NQF level',
    curTrack: 'Track',
    curNotSet: 'not set',
    curCode: 'Module code',
    curCodeAuto: 'suggested',
    curCodeSuggest: 'Suggest',
    curCodeHint: 'Same code as on the module card in Module Mapping: track + level + position within the level. Edit freely.',
    curDistBtn: 'Distribute automatically',
    curDistTip: 'Share the institutional time over the outcomes in proportion to their performance criteria',
    curDistHelpTip: 'How to decide the hours of each learning outcome',
    curDistNeedCredits: 'Enter the module credits first — the institutional time is computed from them.',
    curDistConfirm: 'Some outcomes already have hours. Replace them with the automatic distribution?',
    curDistDone: '{t} h distributed: {list}',
    curHoursAuto: 'auto',
    curHoursAutoHint: 'Calculated automatically from the institutional time — type a value to change it.',
    curHoursManualHint: 'Set by you. Clear the field, or press the button, to return to the automatic value.',
    curFilePrefix: 'Prefix for exported file',
    curFileLevel: 'Level in file name',
    curFilePreview: 'File name:',
    curFileHint: 'Same prefix for every module (e.g. CUR or CBC). These characters are left out of file names: \\ / : * ? " < > |',
    curShortName: 'Short name (file name)',
    curPurposeL: 'Purpose statement',
    curPurposePh: 'Why this module exists — what the learner will be able to do at the end, in one or two sentences.',
    curCreditsL: 'Credits',
    curPrereqL: 'Pre-requisite modules',
    curPrereqNone: 'No other modules in the project.',
    curTimeL: 'Time table',
    curFxCredits: 'Credits',
    curCsBtn: "Suggest credits for all modules",
    curCsHint: "Optional — or type the credits yourself.",
    curCsTitle: "Suggest credits",
    curCsIntro: "Shares a programme total of credits over the modules. Nothing changes until you press Apply; you can edit every value afterwards. Hours keep following credits × hours per credit.",
    curCsTotal: "Total credits of the programme",
    curCsBasis: "Share by",
    curCsLoad: "Training load (Priority Index × difficulty of the module’s tasks)",
    curCsCriteria: "Number of performance criteria",
    curCsNoLoad: "Training load needs rated tasks in Task Verification.",
    curCsColModule: "Module",
    curCsColNow: "Credits now",
    curCsColNew: "Suggested",
    curCsAfter: "Tasks left out of training and unrated tasks count 0; a task used by several modules is shared between them.",
    curCsApply: "Apply to all modules",
    curCsNeedTotal: "Enter the total credits first.",
    curCsApplied: "Credits set for {n} module(s).",
    curCsNoRated: "(no rated tasks)",
    curFxHpc: 'h per credit =',
    curHpcAll: 'Hours per credit apply to all modules.',
    curPctScope: 'Percentages:',
    curPctAll: 'Same for all modules',
    curPctMod: 'This module only',
    curPctAllHint: 'Changing a percentage here changes it for every module that uses the shared percentages.',
    curPctModHint: 'These percentages apply to this module only.',
    curTimeNeedCredits: 'Enter the credits to compute the hours.',
    curTimeFormula: '{c} credits × {h} h = {t} h',
    curInst: 'Institutional',
    curInd: 'Industry',
    curTotalL: 'Total',
    curOverride: 'Use different percentages for this module',
    curOSLinkL: 'Link to the Occupational Standard',
    curOSNone: 'No performance criteria are linked to this module’s outcomes yet.',
    curCompetency: 'Competency {n}',
    curTasksL: 'tasks',
    curLOListL: 'Learning outcomes (module order)',
    curNoLOs: 'This module has no learning outcomes yet.',
    curFilled: '{x}/8 filled',
    curContextPh: 'Workshop, classroom or a real or simulated workplace.',
    curMethodPh: 'How the outcome is taught overall.',
    curDiscPh: 'What the teacher discusses with the learners (talk, questions, explanation).',
    curDemoPh: 'What the teacher shows and does in front of the learners.',
    curPracPh: 'What the learners do themselves, hands-on.',
    curSelfPh: 'What learners look up or prepare on their own.',
    curSuggestCriteria: 'Suggest from criteria',
    curSuggestCriteriaNone: 'This outcome has no linked performance criteria.',
    curSuggestCriteriaDone: '{n} statement(s) added',
    curNothingNew: 'Nothing new to add.',
    curMethodChips: 'Quick add:',
    mDirectObs: 'Direct observation',
    mOral: 'Oral questions',
    mPracTest: 'Practical test',
    mProduct: 'Product check',
    curLOHours: 'Duration (hours)',
    curLOHoursWarn: 'The outcome hours add up to {a} h, but the module’s institutional time is {b} h.',
    curAdd: 'Add',
    curRemove: 'Remove',
    curItemPh: 'Type an item',
    curSuggestTA: 'Suggest from Task Analysis',
    curTANone: 'No tools or safety items were found in the Task Analysis of the tasks linked to this module.',
    curTATitle: 'Suggest from Task Analysis',
    curTAIntro: 'Items from the Task Analysis of the tasks behind this module’s outcomes. Choose where each one goes. Items already in a list are not added again, and nothing already there is replaced.',
    curTAAlready: 'already added',
    curTAAddSel: 'Add selected',
    curTAAdded: '{n} item(s) added',
    curResPh: 'Text or a link (https://…)',
    curFacItem: 'Item',
    curFacQty: 'Qty',
    curFacAdd: 'Add facility',
    curSaved: 'Saved',
    curHelpTip: 'Guidelines: writing a module curriculum (CUR)',
    curCancel: 'Cancel',
    curClose: 'Close',
    // export menu + dialog
    mnuOS: 'Occupational Standard (Word)',
    mnuCUR: 'Module Curriculum — CUR (Word)…',
    mnuCBC: 'CBC (TESDA)',
    mnuSoon: 'Coming soon',
    dlgTitle: 'Export Module Curriculum (CUR)',
    dlgIntro: 'Each module downloads as its own Word file. Click Download next to each module you need — one at a time, so the browser never blocks a batch of downloads.',
    dlgBlank: 'Include empty fields (blank template)',
    dlgBlankHint: 'Prints the structure with empty boxes for experts to fill in by hand.',
    dlgCurrent: 'current',
    dlgDownload: 'Download',
    dlgDone: 'Downloaded',
    dlgNoModules: 'There are no modules to export yet.',
    msgCurExported: 'Module curriculum exported: {file}',
    msgCurCleared: 'Module curriculum cleared',
    lvlShort: 'L{n}',
    hUnit: 'h'
  },
  fr: {
    tabModuleCurriculum: 'Curriculum du module CUR/CBC',
    curEmptyTitle: 'Aucun module pour l’instant',
    curEmptyBody: 'Le curriculum s’écrit module par module. Construisez d’abord vos modules dans la Cartographie des modules — ils apparaîtront ici automatiquement.',
    curGoMM: 'Aller à la Cartographie des modules',
    curSelModule: 'Module',
    curPrev: 'Module précédent',
    curNext: 'Module suivant',
    curComplete: '{p} % complété',
    curExportThis: 'Exporter ce module (Word)',
    curSettings: 'Paramètres du programme',
    curSettingsHint: 'Enregistrés une fois pour tout le projet et utilisés par chaque module. Les heures et les pourcentages se règlent dans le Tableau horaire de chaque module.',
    curProgName: 'Nom du programme',
    curHpc: 'Heures par crédit',
    curGroup: 'Apprenants par groupe',
    curSplitDefault: 'Répartition du temps par défaut (%)',
    curSplitSum: 'Total : {n} %',
    curSplitBad: 'Les pourcentages doivent totaliser 100 % (actuellement {n} %). Les heures sont réparties proportionnellement en attendant.',
    sec1: '1 · En-tête du module',
    sec2: '2 · Résultats d’apprentissage',
    sec3: '3 · Ressources du module',
    curFromMM: 'Depuis la Cartographie des modules',
    curEditInMM: 'Modifier dans la Cartographie des modules',
    curTitle: 'Titre du module',
    curLevel: 'Niveau du CNC',
    curTrack: 'Filière',
    curNotSet: 'non défini',
    curCode: 'Code du module',
    curCodeAuto: 'proposé',
    curCodeSuggest: 'Proposer',
    curCodeHint: 'Le même code que sur la carte du module (Cartographie des modules) : filière + niveau + position dans le niveau. Modifiable.',
    curDistBtn: 'Répartir automatiquement',
    curDistTip: 'Répartir le temps en établissement au prorata des critères de performance de chaque résultat',
    curDistHelpTip: 'Comment fixer les heures de chaque résultat d’apprentissage',
    curDistNeedCredits: 'Saisissez d’abord les crédits du module — le temps en établissement en découle.',
    curDistConfirm: 'Certains résultats ont déjà des heures. Les remplacer par la répartition automatique ?',
    curDistDone: '{t} h réparties : {list}',
    curHoursAuto: 'auto',
    curHoursAutoHint: 'Calculé automatiquement à partir du temps en établissement — saisissez une valeur pour le modifier.',
    curHoursManualHint: 'Valeur saisie. Videz le champ, ou cliquez sur le bouton, pour revenir à la valeur automatique.',
    curFilePrefix: 'Préfixe du fichier exporté',
    curFileLevel: 'Niveau dans le nom du fichier',
    curFilePreview: 'Nom du fichier :',
    curFileHint: 'Même préfixe pour tous les modules (p. ex. CUR ou CBC). Ces caractères sont retirés des noms de fichiers : \\ / : * ? " < > |',
    curShortName: 'Nom court (nom du fichier)',
    curPurposeL: 'Énoncé de l’objectif',
    curPurposePh: 'Pourquoi ce module existe — ce que l’apprenant saura faire à la fin, en une ou deux phrases.',
    curCreditsL: 'Crédits',
    curPrereqL: 'Modules préalables',
    curPrereqNone: 'Aucun autre module dans le projet.',
    curTimeL: 'Tableau horaire',
    curFxCredits: 'Crédits',
    curCsBtn: "Proposer les crédits de tous les modules",
    curCsHint: "Facultatif — ou saisissez les crédits vous-même.",
    curCsTitle: "Proposer les crédits",
    curCsIntro: "Répartit un total de crédits du programme entre les modules. Rien ne change avant « Appliquer » ; chaque valeur reste modifiable. Les heures suivent toujours crédits × heures par crédit.",
    curCsTotal: "Total des crédits du programme",
    curCsBasis: "Répartir selon",
    curCsLoad: "Charge de formation (indice de priorité × difficulté des tâches du module)",
    curCsCriteria: "Nombre de critères de performance",
    curCsNoLoad: "La charge de formation demande des tâches évaluées dans la vérification.",
    curCsColModule: "Module",
    curCsColNow: "Crédits actuels",
    curCsColNew: "Proposés",
    curCsAfter: "Les tâches non retenues et non évaluées comptent 0 ; une tâche utilisée par plusieurs modules est partagée entre eux.",
    curCsApply: "Appliquer à tous les modules",
    curCsNeedTotal: "Saisissez d’abord le total des crédits.",
    curCsApplied: "Crédits fixés pour {n} module(s).",
    curCsNoRated: "(aucune tâche évaluée)",
    curFxHpc: 'h par crédit =',
    curHpcAll: 'Les heures par crédit s’appliquent à tous les modules.',
    curPctScope: 'Pourcentages :',
    curPctAll: 'Identiques pour tous les modules',
    curPctMod: 'Ce module uniquement',
    curPctAllHint: 'Modifier un pourcentage ici le modifie pour tous les modules qui utilisent les pourcentages communs.',
    curPctModHint: 'Ces pourcentages ne s’appliquent qu’à ce module.',
    curTimeNeedCredits: 'Saisissez les crédits pour calculer les heures.',
    curTimeFormula: '{c} crédits × {h} h = {t} h',
    curInst: 'Établissement',
    curInd: 'Entreprise',
    curTotalL: 'Total',
    curOverride: 'Utiliser d’autres pourcentages pour ce module',
    curOSLinkL: 'Lien avec la norme professionnelle',
    curOSNone: 'Aucun critère de performance n’est encore lié aux résultats de ce module.',
    curCompetency: 'Compétence {n}',
    curTasksL: 'tâches',
    curLOListL: 'Résultats d’apprentissage (ordre du module)',
    curNoLOs: 'Ce module n’a pas encore de résultats d’apprentissage.',
    curFilled: '{x}/8 remplis',
    curContextPh: 'Atelier, salle de classe ou lieu de travail réel ou simulé.',
    curMethodPh: 'Comment le résultat est enseigné dans l’ensemble.',
    curDiscPh: 'Ce dont le formateur discute avec les apprenants (exposé, questions, explications).',
    curDemoPh: 'Ce que le formateur montre et fait devant les apprenants.',
    curPracPh: 'Ce que les apprenants font eux-mêmes, en pratique.',
    curSelfPh: 'Ce que les apprenants recherchent ou préparent seuls.',
    curSuggestCriteria: 'Proposer depuis les critères',
    curSuggestCriteriaNone: 'Ce résultat n’a aucun critère de performance lié.',
    curSuggestCriteriaDone: '{n} énoncé(s) ajouté(s)',
    curNothingNew: 'Rien de nouveau à ajouter.',
    curMethodChips: 'Ajout rapide :',
    mDirectObs: 'Observation directe',
    mOral: 'Questions orales',
    mPracTest: 'Épreuve pratique',
    mProduct: 'Contrôle du produit',
    curLOHours: 'Durée (heures)',
    curLOHoursWarn: 'Les heures des résultats totalisent {a} h, mais le temps en établissement du module est de {b} h.',
    curAdd: 'Ajouter',
    curRemove: 'Retirer',
    curItemPh: 'Saisissez un élément',
    curSuggestTA: 'Proposer depuis l’analyse des tâches',
    curTANone: 'Aucun outil ni élément de sécurité trouvé dans l’analyse des tâches liées à ce module.',
    curTATitle: 'Proposer depuis l’analyse des tâches',
    curTAIntro: 'Éléments de l’analyse des tâches liées aux résultats de ce module. Choisissez la liste de destination. Les éléments déjà présents ne sont pas ajoutés deux fois, et rien n’est remplacé.',
    curTAAlready: 'déjà ajouté',
    curTAAddSel: 'Ajouter la sélection',
    curTAAdded: '{n} élément(s) ajouté(s)',
    curResPh: 'Texte ou lien (https://…)',
    curFacItem: 'Élément',
    curFacQty: 'Qté',
    curFacAdd: 'Ajouter une installation',
    curSaved: 'Enregistré',
    curHelpTip: 'Recommandations : rédiger un curriculum de module (CUR)',
    curCancel: 'Annuler',
    curClose: 'Fermer',
    mnuOS: 'Norme professionnelle (Word)',
    mnuCUR: 'Curriculum du module — CUR (Word)…',
    mnuCBC: 'CBC (TESDA)',
    mnuSoon: 'Bientôt',
    dlgTitle: 'Exporter le curriculum du module (CUR)',
    dlgIntro: 'Chaque module est téléchargé dans son propre fichier Word. Cliquez sur Télécharger à côté de chaque module voulu — un à la fois, pour que le navigateur ne bloque pas une série de téléchargements.',
    dlgBlank: 'Inclure les champs vides (modèle vierge)',
    dlgBlankHint: 'Imprime la structure avec des cases vides à remplir à la main par les experts.',
    dlgCurrent: 'actuel',
    dlgDownload: 'Télécharger',
    dlgDone: 'Téléchargé',
    dlgNoModules: 'Aucun module à exporter pour l’instant.',
    msgCurExported: 'Curriculum du module exporté : {file}',
    msgCurCleared: 'Curriculum du module effacé',
    lvlShort: 'N{n}',
    hUnit: 'h'
  },
  ar: {
    tabModuleCurriculum: 'منهج الوحدة CUR/CBC',
    curEmptyTitle: 'لا توجد وحدات بعد',
    curEmptyBody: 'يُكتب المنهج لكل وحدة على حدة. ابنِ الوحدات أولاً في تبويب «مواءمة الوحدات التعلمية» وستظهر هنا تلقائياً.',
    curGoMM: 'الانتقال إلى مواءمة الوحدات',
    curSelModule: 'الوحدة',
    curPrev: 'الوحدة السابقة',
    curNext: 'الوحدة التالية',
    curComplete: 'مكتمل {p}%',
    curExportThis: 'تصدير هذه الوحدة (Word)',
    curSettings: 'إعدادات البرنامج',
    curSettingsHint: 'تُحفظ مرة واحدة للمشروع كله وتستخدمها كل الوحدات. الساعات والنسب تُضبط في جدول الوقت لكل وحدة.',
    curProgName: 'اسم البرنامج',
    curHpc: 'ساعات لكل ساعة معتمدة',
    curGroup: 'عدد المتدربين في المجموعة',
    curSplitDefault: 'توزيع الوقت الافتراضي (%)',
    curSplitSum: 'المجموع: {n}%',
    curSplitBad: 'يجب أن يكون مجموع النسب 100% (حالياً {n}%). تُوزَّع الساعات بالتناسب إلى أن تُصحَّح.',
    sec1: '1 · ترويسة الوحدة',
    sec2: '2 · محصلات التعلم',
    sec3: '3 · موارد الوحدة',
    curFromMM: 'من مواءمة الوحدات',
    curEditInMM: 'التعديل في مواءمة الوحدات',
    curTitle: 'عنوان الوحدة',
    curLevel: 'مستوى الإطار الوطني',
    curTrack: 'المسار',
    curNotSet: 'غير محدد',
    curCode: 'رمز الوحدة',
    curCodeAuto: 'مقترح',
    curCodeSuggest: 'اقتراح',
    curCodeHint: 'هو الرمز نفسه في بطاقة الوحدة في مواءمة الوحدات: المسار + المستوى + ترتيب الوحدة داخل المستوى. يمكنك تعديله.',
    curDistBtn: 'توزيع تلقائي',
    curDistTip: 'توزيع الوقت المؤسسي على المحصلات بنسبة معايير الأداء المرتبطة بكل منها',
    curDistHelpTip: 'كيف تُحدَّد ساعات كل محصلة تعلم',
    curDistNeedCredits: 'أدخل الرصيد / الساعات المعتمدة للوحدة أولاً — الوقت المؤسسي يُحسب منه.',
    curDistConfirm: 'بعض المحصلات لها ساعات مسبقاً. هل تستبدلها بالتوزيع التلقائي؟',
    curDistDone: 'وُزِّعت {t} ساعة: {list}',
    curHoursAuto: 'تلقائي',
    curHoursAutoHint: 'محسوبة تلقائياً من الوقت المؤسسي — اكتب قيمة لتغييرها.',
    curHoursManualHint: 'قيمة أدخلتها أنت. امسح الحقل أو اضغط الزر للعودة إلى القيمة التلقائية.',
    curFilePrefix: 'بادئة الملف المُصدَّر',
    curFileLevel: 'المستوى في اسم الملف',
    curFilePreview: 'اسم الملف:',
    curFileHint: 'البادئة نفسها لكل الوحدات (مثل CUR أو CBC). هذه الرموز تُحذف من أسماء الملفات: \\ / : * ? " < > |',
    curShortName: 'اسم مختصر (لاسم الملف)',
    curPurposeL: 'بيان الغرض',
    curPurposePh: 'لماذا وُجدت هذه الوحدة — ما الذي سيستطيع المتدرب فعله في نهايتها، في جملة أو جملتين.',
    curCreditsL: 'الرصيد / الساعات المعتمدة',
    curPrereqL: 'الوحدات المتطلبة سابقاً',
    curPrereqNone: 'لا توجد وحدات أخرى في المشروع.',
    curTimeL: 'جدول الوقت',
    curFxCredits: 'الرصيد',
    curCsBtn: "اقترح أرصدة جميع الوحدات",
    curCsHint: "اختياري — أو أدخل الأرصدة بنفسك.",
    curCsTitle: "اقتراح الأرصدة",
    curCsIntro: "يوزّع مجموع أرصدة البرنامج على الوحدات. لا يتغير شيء قبل الضغط على «تطبيق»، ويمكنك تعديل كل قيمة بعدها. وتبقى الساعات = الأرصدة × ساعات الرصيد.",
    curCsTotal: "مجموع أرصدة البرنامج",
    curCsBasis: "التوزيع حسب",
    curCsLoad: "عبء التدريب (معامل الأولوية × صعوبة مهام الوحدة)",
    curCsCriteria: "عدد معايير الأداء",
    curCsNoLoad: "عبء التدريب يحتاج مهاماً مقيّمة في تبويب التحقق من المهام.",
    curCsColModule: "الوحدة",
    curCsColNow: "الأرصدة الحالية",
    curCsColNew: "المقترحة",
    curCsAfter: "المهام غير المختارة للتدريب وغير المقيّمة تُحسب صفراً، والمهمة المشتركة بين عدة وحدات يُقسم وزنها بينها.",
    curCsApply: "تطبيق على جميع الوحدات",
    curCsNeedTotal: "أدخل مجموع الأرصدة أولاً.",
    curCsApplied: "تم تحديد أرصدة {n} وحدة.",
    curCsNoRated: "(لا مهام مقيّمة)",
    curFxHpc: 'ساعة لكل ساعة معتمدة =',
    curHpcAll: 'عدد الساعات لكل ساعة معتمدة يُطبَّق على جميع الوحدات.',
    curPctScope: 'النسب:',
    curPctAll: 'موحّدة لكل الوحدات',
    curPctMod: 'خاصة بهذه الوحدة',
    curPctAllHint: 'تغيير أي نسبة هنا يغيّرها لكل الوحدات التي تستخدم النسب الموحّدة.',
    curPctModHint: 'هذه النسب تخص هذه الوحدة فقط.',
    curTimeNeedCredits: 'أدخل الرصيد لحساب الساعات.',
    curTimeFormula: '{c} ساعة معتمدة × {h} = {t} ساعة',
    curInst: 'المؤسسة',
    curInd: 'موقع العمل',
    curTotalL: 'المجموع',
    curOverride: 'استخدام نسب مختلفة لهذه الوحدة',
    curOSLinkL: 'الربط بالمعيار المهني',
    curOSNone: 'لم تُربط بعد أي معايير أداء بمحصلات هذه الوحدة.',
    curCompetency: 'الكفاءة {n}',
    curTasksL: 'المهام',
    curLOListL: 'محصلات التعلم (بترتيب الوحدة)',
    curNoLOs: 'لا توجد محصلات تعلم في هذه الوحدة بعد.',
    curFilled: '{x}/8 مكتملة',
    curContextPh: 'ورشة أو قاعة دراسية أو موقع عمل حقيقي أو محاكى.',
    curMethodPh: 'كيف تُدرَّس المحصلة بصورة عامة.',
    curDiscPh: 'ما يناقشه المدرب مع المتدربين (شرح، أسئلة، حوار).',
    curDemoPh: 'ما يعرضه المدرب وينفّذه أمام المتدربين.',
    curPracPh: 'ما ينفّذه المتدربون بأنفسهم عملياً.',
    curSelfPh: 'ما يبحث عنه المتدربون أو يحضّرونه بأنفسهم.',
    curSuggestCriteria: 'اقتراح من معايير الأداء',
    curSuggestCriteriaNone: 'لا توجد معايير أداء مرتبطة بهذه المحصلة.',
    curSuggestCriteriaDone: 'أُضيفت {n} عبارة',
    curNothingNew: 'لا يوجد جديد لإضافته.',
    curMethodChips: 'إضافة سريعة:',
    mDirectObs: 'الملاحظة المباشرة',
    mOral: 'أسئلة شفوية',
    mPracTest: 'اختبار عملي',
    mProduct: 'فحص المنتج',
    curLOHours: 'المدة (ساعات)',
    curLOHoursWarn: 'مجموع ساعات المحصلات {a} ساعة، بينما الوقت المؤسسي للوحدة {b} ساعة.',
    curAdd: 'إضافة',
    curRemove: 'حذف',
    curItemPh: 'اكتب عنصراً',
    curSuggestTA: 'اقتراح من تحليل المهام',
    curTANone: 'لم يُعثر على عدد أو عناصر سلامة في تحليل المهام المرتبطة بهذه الوحدة.',
    curTATitle: 'اقتراح من تحليل المهام',
    curTAIntro: 'عناصر من تحليل المهام التي تقوم عليها محصلات هذه الوحدة. اختر القائمة المناسبة لكل عنصر. العناصر الموجودة مسبقاً لا تُضاف مرة ثانية، ولا يُستبدل شيء موجود.',
    curTAAlready: 'مضاف مسبقاً',
    curTAAddSel: 'إضافة المحدد',
    curTAAdded: 'أُضيف {n} عنصر',
    curResPh: 'نص أو رابط (https://…)',
    curFacItem: 'العنصر',
    curFacQty: 'العدد',
    curFacAdd: 'إضافة مرفق',
    curSaved: 'تم الحفظ',
    curHelpTip: 'إرشادات: كتابة منهج الوحدة (CUR)',
    curCancel: 'إلغاء',
    curClose: 'إغلاق',
    mnuOS: 'المعيار المهني (Word)',
    mnuCUR: 'منهج الوحدة — CUR (Word)…',
    mnuCBC: 'CBC (TESDA)',
    mnuSoon: 'قريباً',
    dlgTitle: 'تصدير منهج الوحدة (CUR)',
    dlgIntro: 'تُنزَّل كل وحدة في ملف Word مستقل. اضغط «تنزيل» بجانب كل وحدة تحتاجها — واحدة في كل مرة، كي لا يمنع المتصفح التنزيلات المتعددة.',
    dlgBlank: 'تضمين الحقول الفارغة (قالب فارغ)',
    dlgBlankHint: 'يطبع البنية بخانات فارغة ليملأها الخبراء يدوياً.',
    dlgCurrent: 'الحالية',
    dlgDownload: 'تنزيل',
    dlgDone: 'تم التنزيل',
    dlgNoModules: 'لا توجد وحدات للتصدير بعد.',
    msgCurExported: 'تم تصدير منهج الوحدة: {file}',
    msgCurCleared: 'تم مسح منهج الوحدة',
    lvlShort: 'م{n}',
    hUnit: 'ساعة'
  }
};

/* Fixed CUR labels — the wording printed in the Word document and used
   as field labels on screen, so the two can never disagree. Order and
   wording follow the expert template, with its inconsistencies fixed
   on purpose ("Self-directed learning" everywhere, "learning units"). */
export const _L = {
  en: {
    curModule: 'Module', curPurpose: 'Purpose statements', curNqfLevel: 'NQF Level', curCredits: 'Credits',
    curPrereq: 'Pre-requisites modules', curInstTime: 'Indicative Institutional Time',
    curIndTime: 'Indicative Industry Attachment', curTotal100: 'Total 100%', curTheory: 'Theory',
    curPractical: 'Practical', curFormative: 'Formative Assess', curPractice: 'Practice',
    curSummative: 'Summative Assess', curHours: 'Hours', curProgram: 'The program',
    curOSLink: 'Link to the occupational standard',
    curOSLinkLead: 'Link to the following performance criteria in the Occupational Standard:',
    curOSTask: 'Occupational standard task:', curLOs: 'Learning outcomes',
    curLOsLead: 'After completing the learning units within this module, learners will be able to:',
    curLOn: 'Learning outcome {n}', curContext: 'Learning context',
    curMethodology: 'Teaching and learning methodology', curDiscussion: 'Teacher-led discussion',
    curDemonstration: 'Teacher demonstration', curPracticeL: 'Learners will practice',
    curSelfDirected: 'Self-directed learning', curAssessStatements: 'Formative Assessment Statements',
    curAssessMethods: 'Formative Assessment Method', curTools: 'Tools needed for this module',
    curEquipment: 'Equipment needed for this module', curPPE: 'Personal protective equipment (per learner)',
    curMaterials: 'Materials needed for this module', curResources: 'Recommended resources for this module',
    curLearnerGuide: 'Learner’s guide to this module',
    curFacilities: 'Physical facilities (for {n} learners) for this module', curQty: 'Quantity',
    curDefaultContext: 'Workshop, classroom or a real or simulated workplace.',
    curLevelN: 'Level {n}', curPC: 'Performance criteria', curDurationH: 'Duration (hours)'
  },
  fr: {
    curModule: 'Module', curPurpose: 'Énoncé de l’objectif', curNqfLevel: 'Niveau du CNC', curCredits: 'Crédits',
    curPrereq: 'Modules préalables', curInstTime: 'Temps indicatif en établissement',
    curIndTime: 'Stage indicatif en entreprise', curTotal100: 'Total 100 %', curTheory: 'Théorie',
    curPractical: 'Pratique', curFormative: 'Évaluation formative', curPractice: 'Pratique en entreprise',
    curSummative: 'Évaluation sommative', curHours: 'heures', curProgram: 'Le programme',
    curOSLink: 'Lien avec la norme professionnelle',
    curOSLinkLead: 'Lien avec les critères de performance suivants de la norme professionnelle :',
    curOSTask: 'Tâches de la norme professionnelle :', curLOs: 'Résultats d’apprentissage',
    curLOsLead: 'À l’issue des unités d’apprentissage de ce module, les apprenants seront capables de :',
    curLOn: 'Résultat d’apprentissage {n}', curContext: 'Contexte d’apprentissage',
    curMethodology: 'Méthodologie d’enseignement et d’apprentissage', curDiscussion: 'Discussion dirigée par le formateur',
    curDemonstration: 'Démonstration par le formateur', curPracticeL: 'Les apprenants s’exerceront',
    curSelfDirected: 'Apprentissage autonome', curAssessStatements: 'Énoncés d’évaluation formative',
    curAssessMethods: 'Méthode d’évaluation formative', curTools: 'Outils nécessaires pour ce module',
    curEquipment: 'Équipements nécessaires pour ce module', curPPE: 'Équipements de protection individuelle (par apprenant)',
    curMaterials: 'Matériaux nécessaires pour ce module', curResources: 'Ressources recommandées pour ce module',
    curLearnerGuide: 'Guide de l’apprenant pour ce module',
    curFacilities: 'Installations physiques (pour {n} apprenants) pour ce module', curQty: 'Quantité',
    curDefaultContext: 'Atelier, salle de classe ou lieu de travail réel ou simulé.',
    curLevelN: 'Niveau {n}', curPC: 'Critères de performance', curDurationH: 'Durée (heures)'
  },
  ar: {
    curModule: 'الوحدة', curPurpose: 'بيان الغرض', curNqfLevel: 'مستوى الإطار الوطني للمؤهلات',
    curCredits: 'الرصيد / الساعات المعتمدة', curPrereq: 'الوحدات المتطلبة سابقاً',
    curInstTime: 'الوقت المؤسسي التقديري', curIndTime: 'التدريب التقديري في موقع العمل',
    curTotal100: 'المجموع 100%', curTheory: 'نظري', curPractical: 'عملي', curFormative: 'تقييم تكويني',
    curPractice: 'تطبيق في موقع العمل', curSummative: 'تقييم ختامي', curHours: 'ساعة', curProgram: 'البرنامج',
    curOSLink: 'الربط بالمعيار المهني',
    curOSLinkLead: 'ترتبط هذه الوحدة بمعايير الأداء الآتية في المعيار المهني:',
    curOSTask: 'مهام المعيار المهني:', curLOs: 'محصلات التعلم',
    curLOsLead: 'بعد إكمال وحدات التعلم ضمن هذه الوحدة، سيكون المتدربون قادرين على:',
    curLOn: 'محصلة التعلم {n}', curContext: 'سياق التعلم',
    curMethodology: 'منهجية التعليم والتعلم', curDiscussion: 'نقاش يقوده المدرب',
    curDemonstration: 'عرض توضيحي من المدرب', curPracticeL: 'ممارسة المتدربين',
    curSelfDirected: 'التعلم الذاتي', curAssessStatements: 'عبارات التقييم التكويني',
    curAssessMethods: 'طريقة التقييم التكويني', curTools: 'الأدوات اللازمة لهذه الوحدة',
    curEquipment: 'الأجهزة والمعدات اللازمة لهذه الوحدة', curPPE: 'معدات الوقاية الشخصية (لكل متدرب)',
    curMaterials: 'المواد اللازمة لهذه الوحدة', curResources: 'المصادر الموصى بها لهذه الوحدة',
    curLearnerGuide: 'دليل المتدرب لهذه الوحدة',
    curFacilities: 'المرافق المادية (لـ {n} متدرباً) لهذه الوحدة', curQty: 'العدد',
    curDefaultContext: 'ورشة أو قاعة دراسية أو موقع عمل حقيقي أو محاكى.',
    curLevelN: 'المستوى {n}', curPC: 'معايير الأداء', curDurationH: 'المدة (ساعات)'
  }
};

// ── Guidelines (same look as the Learning Outcomes / Module Mapping guides)
export const _GUIDE = {
  en: {
    title: 'Writing a module curriculum (CUR)',
    intro: 'A CUR turns one module into a teaching plan: what it is for, how long it takes, how each learning outcome is taught and checked, and what the workshop needs. The examples below use a general computer maintenance module, “Assemble and maintain computer hardware”.',
    sections: [
      { h: '🏷️ Header', items: [
        '<strong>Module code</strong> — track + level + position of the module in that level. Example: <em><bdi>CMT 1-1</bdi></em> (first module of level 1).',
        '<strong>Purpose statement</strong> — why the module exists and what learners will be able to do at the end, in one or two sentences. Example: <em>To enable learners to use hand tools, assemble computer components and install peripherals according to manufacturer’s specifications.</em>',
        '<strong>Credits</strong> — the weight of the module. You enter only the credits; the hours are calculated for you: credits × hours per credit (set in the Time table), then shared out by the time-split percentages, in whole hours that always add up to the total. Example with 50 hours per credit: 3 credits = 150 h → Theory 15, Practical 67, Formative assessment 8 (Institutional 90 h) · Industry practice 52, Summative assessment 8 (Industry 60 h).',
        '<strong>Pre-requisite modules</strong> — tick the modules a learner must complete before this one. Example: <em>a workplace safety module</em> before a module that uses power tools.' ] },
      { h: '🎯 For each learning outcome', items: [
        '<strong>Learning context</strong> — where the learning takes place. Example: <em>Workshop, classroom or a real or simulated workplace.</em>',
        '<strong>Teaching and learning methodology</strong> — the overall approach. Example: <em>The teacher introduces the hand tools used to open and fasten computer parts (screwdrivers, cutters, pliers).</em>',
        '<strong>Teacher-led discussion</strong> — what the teacher talks through and asks. Example: <em>The teacher leads a discussion on each tool, when it is used and the safety risks.</em>',
        '<strong>Teacher demonstration</strong> — what the teacher shows and does in front of the learners. Example: <em>The teacher demonstrates how to use each tool correctly and safely.</em>',
        '<strong>Learners will practice</strong> — what the learners do with their own hands. Example: <em>Learners open and close a computer case using the correct tools.</em>',
        '<strong>Self-directed learning</strong> — what learners look up or prepare on their own. Example: <em>Searching for other types of tools and how they are used.</em>',
        '<strong>Formative assessment statements</strong> — short, observable checks, numbered n-1, n-2… (n = the outcome’s number). “Suggest from criteria” copies the outcome’s performance criteria as a starting point. Example: <em>1-1 Uses screwdrivers and hand tools correctly and safely.</em>',
        '<strong>Formative assessment method</strong> — how each check is carried out. Example: <em>Direct observation; oral questions.</em>',
        '<strong>Duration (hours)</strong> — optional. When filled, the outcome hours should add up to the module’s institutional time; a warning shows if they do not.' ] },
      { h: '💡 Discussion and demonstration are different', items: [
        'Discussion = the teacher talks, explains and asks questions. Demonstration = the teacher shows and does the task. Write each in its own field so the teaching plan stays clear.' ] },
      { h: '🧰 Resources', items: [
        '<strong>Tools</strong> — items held in the hand: <em>screwdrivers, tweezers, multimeter</em>.',
        '<strong>Equipment</strong> — devices and machines: <em>laptop, printer, soldering station, UPS</em>.',
        '<strong>Personal protective equipment (per learner)</strong> — <em>safety goggles, gloves, dust mask</em>.',
        '<strong>Materials</strong> — consumables: <em>A4 paper, printer cartridge, blank discs</em>.',
        '<strong>Recommended resources</strong> — the learner’s guide, books and links.',
        '<strong>Physical facilities</strong> — rooms and furniture with quantities for one group: <em>Classroom 8 m × 7 m — 1; Desks — 15</em>.',
        '“Suggest from Task Analysis” brings in tools and safety items from the tasks behind the outcomes; you choose which list each one goes to.' ] }
    ]
  },
  fr: {
    title: 'Rédiger un curriculum de module (CUR)',
    intro: 'Un CUR transforme un module en plan d’enseignement : à quoi il sert, combien de temps il dure, comment chaque résultat est enseigné et vérifié, et ce dont l’atelier a besoin. Les exemples ci-dessous portent sur un module général de maintenance informatique, « Assembler et entretenir le matériel informatique ».',
    sections: [
      { h: '🏷️ En-tête', items: [
        '<strong>Code du module</strong> — filière + niveau + position du module dans ce niveau. Exemple : <em><bdi>CMT 1-1</bdi></em> (premier module du niveau 1).',
        '<strong>Énoncé de l’objectif</strong> — pourquoi le module existe et ce que l’apprenant saura faire à la fin, en une ou deux phrases. Exemple : <em>Permettre aux apprenants d’utiliser les outils à main, d’assembler les composants d’un ordinateur et d’installer les périphériques selon les spécifications du fabricant.</em>',
        '<strong>Crédits</strong> — le poids du module. Vous saisissez seulement les crédits ; les heures sont calculées : crédits × heures par crédit (réglées dans le Tableau horaire), puis réparties selon les pourcentages, en heures entières dont la somme égale toujours le total. Exemple avec 50 h par crédit : 3 crédits = 150 h → Théorie 15, Pratique 67, Évaluation formative 8 (Établissement 90 h) · Pratique en entreprise 52, Évaluation sommative 8 (Entreprise 60 h).',
        '<strong>Modules préalables</strong> — cochez les modules à terminer avant celui-ci. Exemple : <em>un module de sécurité au travail</em> avant un module qui utilise des outils électriques.' ] },
      { h: '🎯 Pour chaque résultat d’apprentissage', items: [
        '<strong>Contexte d’apprentissage</strong> — où l’apprentissage a lieu. Exemple : <em>Atelier, salle de classe ou lieu de travail réel ou simulé.</em>',
        '<strong>Méthodologie</strong> — l’approche générale. Exemple : <em>Le formateur présente les outils à main servant à ouvrir et fixer les pièces (tournevis, pinces coupantes, pinces).</em>',
        '<strong>Discussion dirigée</strong> — ce que le formateur explique et demande. Exemple : <em>Il anime une discussion sur chaque outil, son usage et les risques.</em>',
        '<strong>Démonstration</strong> — ce que le formateur montre et fait devant les apprenants. Exemple : <em>Il montre comment utiliser chaque outil correctement et en sécurité.</em>',
        '<strong>Les apprenants s’exerceront</strong> — ce que les apprenants font eux-mêmes. Exemple : <em>Ouvrir et refermer un boîtier avec les bons outils.</em>',
        '<strong>Apprentissage autonome</strong> — ce qu’ils recherchent ou préparent seuls. Exemple : <em>Rechercher d’autres types d’outils et leur utilisation.</em>',
        '<strong>Énoncés d’évaluation formative</strong> — vérifications courtes et observables, numérotées n-1, n-2… (n = numéro du résultat). « Proposer depuis les critères » copie les critères de performance pour démarrer. Exemple : <em>1-1 Utilise correctement et en sécurité les tournevis et outils à main.</em>',
        '<strong>Méthode d’évaluation formative</strong> — comment chaque vérification se fait. Exemple : <em>Observation directe ; questions orales.</em>',
        '<strong>Durée (heures)</strong> — facultative. Si elle est remplie, la somme des heures des résultats doit égaler le temps en établissement ; un avertissement s’affiche sinon.' ] },
      { h: '💡 Discussion et démonstration sont différentes', items: [
        'Discussion = le formateur parle, explique et pose des questions. Démonstration = le formateur montre et réalise la tâche. Écrivez chacune dans son champ pour un plan clair.' ] },
      { h: '🧰 Ressources', items: [
        '<strong>Outils</strong> — objets tenus en main : <em>tournevis, pincettes, multimètre</em>.',
        '<strong>Équipements</strong> — appareils et machines : <em>ordinateur portable, imprimante, station de soudage, onduleur</em>.',
        '<strong>EPI (par apprenant)</strong> — <em>lunettes, gants, masque anti-poussière</em>.',
        '<strong>Matériaux</strong> — consommables : <em>papier A4, cartouche, disques vierges</em>.',
        '<strong>Ressources recommandées</strong> — guide de l’apprenant, livres et liens.',
        '<strong>Installations physiques</strong> — salles et mobilier avec quantités pour un groupe : <em>Salle 8 m × 7 m — 1 ; Bureaux — 15</em>.',
        '« Proposer depuis l’analyse des tâches » reprend outils et éléments de sécurité des tâches liées ; vous choisissez la liste de chacun.' ] }
    ]
  },
  ar: {
    title: 'كتابة منهج الوحدة (CUR)',
    intro: 'يحوّل منهج الوحدة (CUR) الوحدة إلى خطة تدريس: الغرض منها، ومدتها، وكيف تُدرَّس كل محصلة تعلم وتُقيَّم، وما تحتاجه الورشة. الأمثلة أدناه من وحدة عامة في صيانة الحاسوب بعنوان «تجميع عتاد الحاسوب وصيانته».',
    sections: [
      { h: '🏷️ الترويسة', items: [
        '<strong>رمز الوحدة</strong> — المسار + المستوى + ترتيب الوحدة داخل ذلك المستوى. مثال: <em><bdi>CMT 1-1</bdi></em> (الوحدة الأولى في المستوى 1).',
        '<strong>بيان الغرض</strong> — لماذا وُجدت الوحدة وما الذي سيستطيع المتدرب فعله في نهايتها، في جملة أو جملتين. مثال: <em>تمكين المتدربين من استخدام العدد اليدوية وتجميع مكونات الحاسوب وتنصيب الأجهزة الطرفية وفق مواصفات الصانع.</em>',
        '<strong>الرصيد / الساعات المعتمدة</strong> — وزن الوحدة. تُدخل الرصيد فقط، والساعات تُحسب تلقائياً: الرصيد × الساعات لكل ساعة معتمدة (تُضبط في جدول الوقت)، ثم تُوزَّع حسب نسب توزيع الوقت بساعات صحيحة مجموعها يساوي الإجمالي دائماً. مثال بـ 50 ساعة لكل ساعة معتمدة: 3 = 150 ساعة ← نظري 15، عملي 67، تقييم تكويني 8 (المؤسسة 90 ساعة) · تطبيق في موقع العمل 52، تقييم ختامي 8 (موقع العمل 60 ساعة).',
        '<strong>الوحدات المتطلبة سابقاً</strong> — ضع علامة على الوحدات التي يجب أن يُكملها المتدرب قبل هذه الوحدة. مثال: <em>وحدة السلامة في مكان العمل</em> قبل وحدة تستخدم العدد الكهربائية.' ] },
      { h: '🎯 لكل محصلة تعلم', items: [
        '<strong>سياق التعلم</strong> — أين يحدث التعلم. مثال: <em>ورشة أو قاعة دراسية أو موقع عمل حقيقي أو محاكى.</em>',
        '<strong>منهجية التعليم والتعلم</strong> — الأسلوب العام. مثال: <em>يعرّف المدرب المتدربين بالعدد اليدوية المستخدمة في فتح أجزاء الحاسوب وتثبيتها (المفكات، القطّاعات، الزرادية).</em>',
        '<strong>نقاش يقوده المدرب</strong> — ما يشرحه المدرب ويسأل عنه. مثال: <em>يدير المدرب نقاشاً حول كل عدة ومتى تُستخدم ومخاطرها.</em>',
        '<strong>عرض توضيحي من المدرب</strong> — ما يُريه المدرب وينفّذه أمام المتدربين. مثال: <em>يعرض المدرب طريقة استخدام كل عدة بشكل صحيح وآمن.</em>',
        '<strong>ممارسة المتدربين</strong> — ما ينفّذه المتدربون بأيديهم. مثال: <em>يفتح المتدربون صندوق الحاسوب ويغلقونه بالعدد الصحيحة.</em>',
        '<strong>التعلم الذاتي</strong> — ما يبحث عنه المتدربون أو يحضّرونه بأنفسهم. مثال: <em>البحث عن أنواع أخرى من العدد وطريقة استخدامها.</em>',
        '<strong>عبارات التقييم التكويني</strong> — تحققات قصيرة قابلة للملاحظة، مرقّمة n-1، n-2… (n = رقم المحصلة). زر «اقتراح من معايير الأداء» ينسخ معايير المحصلة كبداية. مثال: <em>1-1 يستخدم المفكات والعدد اليدوية بشكل صحيح وآمن.</em>',
        '<strong>طريقة التقييم التكويني</strong> — كيف يتم كل تحقق. مثال: <em>الملاحظة المباشرة؛ أسئلة شفوية.</em>',
        '<strong>المدة (ساعات)</strong> — اختيارية. عند تعبئتها ينبغي أن يساوي مجموع ساعات المحصلات الوقتَ المؤسسي للوحدة، ويظهر تنبيه إن لم يتساويا.' ] },
      { h: '💡 النقاش يختلف عن العرض التوضيحي', items: [
        'النقاش = المدرب يتحدث ويشرح ويطرح الأسئلة. العرض التوضيحي = المدرب يُري المهمة وينفّذها. اكتب كلاً منهما في خانته لتبقى خطة التدريس واضحة.' ] },
      { h: '🧰 الموارد', items: [
        '<strong>الأدوات</strong> — ما يُمسك باليد: <em>مفكات، ملقط، مقياس متعدد</em>.',
        '<strong>الأجهزة والمعدات</strong> — أجهزة وآلات: <em>حاسوب محمول، طابعة، محطة لحام، جهاز UPS</em>.',
        '<strong>معدات الوقاية الشخصية (لكل متدرب)</strong> — <em>نظارات واقية، قفازات، كمامة</em>.',
        '<strong>المواد</strong> — مستهلكات: <em>ورق A4، حبر طابعة، أقراص فارغة</em>.',
        '<strong>المصادر الموصى بها</strong> — دليل المتدرب والكتب والروابط.',
        '<strong>المرافق المادية</strong> — القاعات والأثاث مع العدد لمجموعة واحدة: <em>قاعة 8م × 7م — 1؛ مكاتب — 15</em>.',
        'زر «اقتراح من تحليل المهام» يجلب العدد وعناصر السلامة من المهام التي تقوم عليها المحصلات، وأنت تختار قائمة كل عنصر.' ] }
    ]
  }
};

export const _DIST_GUIDE = {
  en: {
    title: 'Learning outcome hours — how to decide',
    intro: 'The hours of the learning outcomes share out the module’s institutional time (theory + practical + formative assessment). Industry practice and summative assessment belong to the whole module and are not split over the outcomes. The field is optional; when it is filled, the outcome hours should add up exactly to the institutional time.',
    sections: [
      { h: '⚖️ Automatic hours and “Distribute automatically”', items: [
        'As soon as the module credits are entered, every outcome shows an automatic value (marked “auto”). Typing a number makes it yours; the other automatic outcomes then share what is left. Clearing the field returns it to auto.',
        '“Distribute automatically” returns every outcome of the module to the automatic value.',
        'Shares the institutional time in proportion to the number of performance criteria linked to each outcome (an outcome with none counts as 1).',
        'Whole hours only, and they always add up exactly to the total. Example: 90 h over outcomes with 1, 1 and 2 criteria → 23 + 22 + 45.',
        'It is a documented starting point, not a decision: adjust any value afterwards.' ] },
      { h: '🧭 What to consider when you adjust', items: [
        '<strong>Size of the outcome</strong> — more performance criteria and assessment statements usually need more time.',
        '<strong>Complexity</strong> — an outcome that involves diagnosis, decisions or several steps needs more time than a routine procedure.',
        '<strong>Practical intensity</strong> — outcomes that need repeated hands-on practice on tools or equipment need more time than mostly theoretical ones.',
        '<strong>Learners’ starting point</strong> — new content takes longer than content that builds on an earlier module.',
        '<strong>Resources</strong> — when learners must take turns on limited equipment, allow extra time.' ] },
      { h: '✅ Check', items: [
        'The warning above the outcome cards disappears when the outcome hours add up to the institutional time.',
        'Have the review panel confirm the final distribution.' ] }
    ]
  },
  fr: {
    title: 'Heures des résultats d’apprentissage — comment décider',
    intro: 'Les heures des résultats répartissent le temps en établissement du module (théorie + pratique + évaluation formative). La pratique en entreprise et l’évaluation sommative concernent tout le module et ne sont pas réparties. Le champ est facultatif ; s’il est rempli, la somme doit égaler exactement le temps en établissement.',
    sections: [
      { h: '⚖️ Heures automatiques et « Répartir automatiquement »', items: [
        'Dès que les crédits du module sont saisis, chaque résultat affiche une valeur automatique (marquée « auto »). Saisir un nombre le fixe ; les autres résultats automatiques se partagent le reste. Vider le champ le remet en automatique.',
        '« Répartir automatiquement » remet tous les résultats du module en valeur automatique.',
        'Répartit le temps en établissement au prorata du nombre de critères de performance liés à chaque résultat (un résultat sans critère compte pour 1).',
        'Heures entières uniquement, dont la somme égale toujours le total. Exemple : 90 h pour des résultats à 1, 1 et 2 critères → 23 + 22 + 45.',
        'C’est un point de départ documenté, pas une décision : ajustez ensuite.' ] },
      { h: '🧭 À prendre en compte pour ajuster', items: [
        '<strong>Taille du résultat</strong> — plus de critères et d’énoncés d’évaluation demandent généralement plus de temps.',
        '<strong>Complexité</strong> — diagnostic, prise de décision ou étapes multiples demandent plus de temps qu’une procédure routinière.',
        '<strong>Intensité pratique</strong> — la pratique répétée sur outils ou équipements demande plus de temps que la théorie.',
        '<strong>Acquis des apprenants</strong> — un contenu nouveau prend plus de temps qu’un contenu qui prolonge un module précédent.',
        '<strong>Ressources</strong> — si les apprenants se relaient sur un équipement limité, prévoyez du temps en plus.' ] },
      { h: '✅ Vérifier', items: [
        'L’avertissement au-dessus des cartes disparaît quand la somme égale le temps en établissement.',
        'Faites valider la répartition finale par le comité de validation.' ] }
    ]
  },
  ar: {
    title: 'ساعات محصلات التعلم — كيف تُحدَّد',
    intro: 'ساعات المحصلات توزّع الوقت المؤسسي للوحدة (نظري + عملي + تقييم تكويني). أما التطبيق في موقع العمل والتقييم الختامي فيخصّان الوحدة كلها ولا يُوزَّعان على المحصلات. الحقل اختياري، وعند تعبئته يجب أن يساوي مجموع ساعات المحصلات الوقت المؤسسي بالضبط.',
    sections: [
      { h: '⚖️ الساعات التلقائية وزر «توزيع تلقائي»', items: [
        'بمجرد إدخال رصيد الوحدة تظهر لكل محصلة قيمة تلقائية (عليها شارة «تلقائي»). إذا كتبت رقماً يصبح قيمتك أنت، وتتقاسم المحصلات التلقائية الأخرى ما تبقّى. مسح الحقل يعيده إلى التلقائي.',
        'زر «توزيع تلقائي» يعيد كل محصلات الوحدة إلى القيم التلقائية.',
        'يقسم الوقت المؤسسي بنسبة عدد معايير الأداء المرتبطة بكل محصلة (المحصلة التي لا معايير لها تُحسب 1).',
        'بساعات صحيحة فقط، ومجموعها يساوي الإجمالي دائماً. مثال: 90 ساعة على محصلات فيها 1 و1 و2 من المعايير ← 23 + 22 + 45.',
        'هو نقطة بداية موثقة وليس قراراً نهائياً؛ عدّل أي قيمة بعده.' ] },
      { h: '🧭 ما تراعيه عند التعديل', items: [
        '<strong>حجم المحصلة</strong> — كثرة معايير الأداء وعبارات التقييم تحتاج عادةً وقتاً أطول.',
        '<strong>التعقيد</strong> — المحصلة التي فيها تشخيص أو اتخاذ قرار أو خطوات متعددة تحتاج وقتاً أكثر من إجراء روتيني.',
        '<strong>الكثافة العملية</strong> — المحصلة التي تتطلب تمريناً متكرراً على العدد والأجهزة تحتاج وقتاً أكثر من المحصلة النظرية غالباً.',
        '<strong>خلفية المتدربين</strong> — المحتوى الجديد يأخذ وقتاً أطول من محتوى يبني على وحدة سابقة.',
        '<strong>الموارد</strong> — إذا تناوب المتدربون على أجهزة محدودة فأضف وقتاً لذلك.' ] },
      { h: '✅ التحقق', items: [
        'يختفي التنبيه أعلى بطاقات المحصلات عندما يساوي مجموع ساعاتها الوقت المؤسسي.',
        'اعرض التوزيع النهائي على لجنة المراجعة للمصادقة.' ] }
    ]
  }
};
